import {
  Factory,
  Building2,
  Warehouse,
  Guitar,
  Ban,
  School,
  ShoppingBag,
  Plane,
  Users,
  Truck,
  Palette,
  Shirt,
  Building,
  Cpu,
  Wheat,
  LandPlot,
  Sailboat,
  Construction,
  Paintbrush2,
  FlaskConical,
  HeartPulse,
  Boxes,
  Database,
  Hammer,
  Wrench,
  Newspaper,
  Fish,
  Fuel,
  PaintRoller,
} from 'lucide-react';

export const iconMap: { [key: string]: React.ComponentType<any> } = {
  AERONAUTICA: Plane,
  AGRICOLA: Wheat,
  ALIMENTICIA: ShoppingBag,
  AUTOMOTRIZ: Truck,
  AUTOPARTISTA: Wrench,
  AVICOLA: Ban,
  CARPINTERIA: Hammer,
  CEMENTERA: Building,
  CONSTRUCCION: Construction,
  VIALIDAD: LandPlot,
  ELECTRICA: Cpu,
  ELECTRONICA: Cpu,
  FARMACEUTICA: HeartPulse,
  FERRETERIA: Hammer,
  FRIGORIFICA: Warehouse,
  FRIGORIFICO: Warehouse,
  GAS: Fuel,
  LABORATORIO: FlaskConical,
  LIMPIEZA: Paintbrush2,
  LOGISTICA: Boxes,
  MANUFACTURA: Factory,
  METALMECANICA: Wrench,
  METALURRGICA: Factory,
  MINERA: Construction,
  NAVIERA: Sailboat,
  PAPELERA: Newspaper,
  PESQUERA: Fish,
  PETROLEO: Fuel,
  PETROLERA: Fuel,
  PETROQUIMICA: Fuel,
  PINTURA: PaintRoller,
  QUIMICA: FlaskConical,
  SALUD: HeartPulse,
  SIDERURGICA: Factory,
  SOLDADURA: Wrench,
  TABACALERA: Ban,
  TRANSPORTE: Truck,
};

export const industries = [
    {
        name: 'AERONAUTICA',
        description: 'Soluciones de seguridad para la industria aeronáutica.',
        image: 'https://images.unsplash.com/photo-1559083156-7d2956b9430c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'AGRICOLA',
        description: 'Soluciones de seguridad para la industria agrícola.',
        image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'ALIMENTICIA',
        description: 'Soluciones de seguridad para la industria alimenticia.',
        image: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'AUTOMOTRIZ',
        description: 'Soluciones de seguridad para la industria automotriz.',
        image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'AUTOPARTISTA',
        description: 'Soluciones de seguridad para la industria de autopartes.',
        image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'AVICOLA',
        description: 'Soluciones de seguridad para la industria avícola.',
        image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'CARPINTERIA',
        description: 'Soluciones de seguridad para carpinterías.',
        image: 'https://images.unsplash.com/photo-1622021142947-da7dedc7c39a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'CEMENTERA',
        description: 'Soluciones de seguridad para la industria cementera.',
        image: 'https://via.placeholder.com/300x200?text=Cementera',
    },
    {
        name: 'CONSTRUCCION',
        description: 'Soluciones de seguridad para la industria de la construcción.',
        image: 'https://images.unsplash.com/photo-1541976590-713941681591?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'VIALIDAD',
        description: 'Soluciones de seguridad para la industria de vialidad.',
        image: 'https://via.placeholder.com/300x200?text=Vialidad',
    },
    {
        name: 'ELECTRICA',
        description: 'Soluciones de seguridad para la industria eléctrica.',
        image: 'https://via.placeholder.com/300x200?text=Electrica',
    },
    {
        name: 'ELECTRONICA',
        description: 'Soluciones de seguridad para la industria electrónica.',
        image: 'https://via.placeholder.com/300x200?text=Electronica',
    },
    {
        name: 'FARMACEUTICA',
        description: 'Soluciones de seguridad para la industria farmacéutica.',
        image: 'https://via.placeholder.com/300x200?text=Farmaceutica',
    },
    {
        name: 'FERRETERIA',
        description: 'Soluciones de seguridad para ferreterías.',
        image: 'https://via.placeholder.com/300x200?text=Ferreteria',
    },
    {
        name: 'FRIGORIFICA',
        description: 'Soluciones de seguridad para la industria frigorífica.',
        image: 'https://via.placeholder.com/300x200?text=Frigorifica',
    },
    {
        name: 'FRIGORIFICO',
        description: 'Soluciones de seguridad para frigoríficos.',
        image: 'https://via.placeholder.com/300x200?text=Frigorifico',
    },
    {
        name: 'GAS',
        description: 'Soluciones de seguridad para la industria del gas.',
        image: 'https://via.placeholder.com/300x200?text=Gas',
    },
    {
        name: 'LABORATORIO',
        description: 'Soluciones de seguridad para laboratorios.',
        image: 'https://via.placeholder.com/300x200?text=Laboratorio',
    },
    {
        name: 'LIMPIEZA',
        description: 'Soluciones de seguridad para la industria de la limpieza.',
        image: 'https://via.placeholder.com/300x200?text=Limpieza',
    },
    {
        name: 'LOGISTICA',
        description: 'Soluciones de seguridad para la industria logística.',
        image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'MANUFACTURA',
        description: 'Soluciones de seguridad para la industria manufacturera.',
        image: 'https://images.unsplash.com/photo-1563874257547-d19fbb71b46c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'METALMECANICA',
        description: 'Soluciones de seguridad para la industria metalmecánica.',
        image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'METALURGICA',
        description: 'Soluciones de seguridad para la industria metalúrgica.',
        image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'MINERA',
        description: 'Soluciones de seguridad para la industria minera.',
        image: 'https://images.unsplash.com/photo-1507644331669-5cc76957c2d0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'MINERIA',
        description: 'Soluciones de seguridad para la industria minera.',
        image: 'https://via.placeholder.com/300x200?text=Mineria',
    },
    {
        name: 'NAVIERA',
        description: 'Soluciones de seguridad para la industria naviera.',
        image: 'https://via.placeholder.com/300x200?text=Naviera',
    },
    {
        name: 'PAPELERA',
        description: 'Soluciones de seguridad para la industria papelera.',
        image: 'https://via.placeholder.com/300x200?text=Papelera',
    },
    {
        name: 'PESQUERA',
        description: 'Soluciones de seguridad para la industria pesquera.',
        image: 'https://via.placeholder.com/300x200?text=Pesquera',
    },
    {
        name: 'PETROLEO',
        description: 'Soluciones de seguridad para la industria del petróleo.',
        image: 'https://via.placeholder.com/300x200?text=Petroleo',
    },
    {
        name: 'PETROLERA',
        description: 'Soluciones de seguridad para la industria petrolera.',
        image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'PETROQUIMICA',
        description: 'Soluciones de seguridad para la industria petroquímica.',
        image: 'https://via.placeholder.com/300x200?text=Petroquimica',
    },
    {
        name: 'PINTURA',
        description: 'Soluciones de seguridad para la industria de la pintura.',
        image: 'https://via.placeholder.com/300x200?text=Pintura',
    },
    {
        name: 'QUIMICA',
        description: 'Soluciones de seguridad para la industria química.',
        image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'SALUD',
        description: 'Soluciones de seguridad para el sector salud.',
        image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    },
    {
        name: 'SIDERURGICA',
        description: 'Soluciones de seguridad para la industria siderúrgica.',
        image: 'https://via.placeholder.com/300x200?text=Siderurgica',
    },
    {
        name: 'SOLDADURA',
        description: 'Soluciones de seguridad para la industria de la soldadura.',
        image: 'https://via.placeholder.com/300x200?text=Soldadura',
    },
    {
        name: 'TABACALERA',
        description: 'Soluciones de seguridad para la industria tabacalera.',
        image: 'https://via.placeholder.com/300x200?text=Tabacalera',
    },
    {
        name: 'TRANSPORTE',
        description: 'Soluciones de seguridad para la industria del transporte.',
        image: 'https://via.placeholder.com/300x200?text=Transporte',
    },
    {
        name: 'VIALIDAD',
        description: 'Soluciones de seguridad para la industria de vialidad.',
        image: 'https://via.placeholder.com/300x200?text=Vialidad',
    },
];
